# Generated by Django 4.2.7 on 2023-11-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_song_messageattachment_messages_song_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='date',
            field=models.DateField(auto_created=True, default=None),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=25),
        ),
    ]
